- README.txt
This corrects the acronym in the DESCRIPTION.
> Fix a typo in README.txt

- src/Makefile
- src/debugs.c
- src/dwsolv.c
- src/main.c
- src/readqubo.c
- src/solver.c
- src/util.c
Cleaned up code and adjusted comments. 
Attempted to make several areas more clear. Cleaned up makefile a little. Moved some code to new lines to make it easier to read. Added detail where appropriate.
Modified the tabu_search function. 
removed the GOTOs, fixed the comparisons to do what they implied to do before AND covered all of the possible ranges
> Clean up and bug fixes

- src/dwsolv.c
- src/extern.h
- src/main.c
- tests/solver_reduce.c
- tests/solver_reduce.cpp
- tests/util_malloc.cpp
Remove unused variables.
Remove variables externed but not used in more than one place.
> Prune variables.

- src/solver.c
- src/util.c
- removed Rtrn variable
- added return value enum
- cleaned up some of the formatting
- improved readability of code
> updated manage_Q function

- src/util.c
This reverts commit 42a7d751416e678d71ca86fc335316427959b0ae.
This is too big for some folk's stack pointers.
> Revert "Remove an extra call to malloc."

- src/Makefile
- src/debugs.c
- src/dwsolv.c
- src/include.h
- src/main.c
- src/readqubo.c
- src/solver.c
- src/util.c
Mostly variable renaming and switching to c99 idioms.
> Bundle of mostly cosmetic changes

- src/readqubo.c
> Fixed small typo in error reporting for number of nodes

- README.txt
- contrib.txt
Signed-off-by: Charles Chan <charleswhchan@users.noreply.github.com>
> Fix name of LICENSE file in README.txt and contrib.txt

- src/include.h
> Fix build on Haiku

- src/dwsolv.c
- src/main.c
- src/make.bash
- src/readqubo.c
- src/solver.c
- src/util.c
Fix typos in comments and print statements
> Signed-off-by: S Davis <myriagon@sddw.net>

- tests/qbsTest_bqp_Target.sh
Signed-off-by: S Davis <myriagon@sddw.net>
> Improve tabular output using printf to align columns

- python/dwave_qbsolv/dimod_wrapper.py
- python/dwave_qbsolv/qbsolv_binding.pyx
Fix typos in dimod_wrapper.py and qbsolv_binding.pyx
> Fix typos in dimod_wrapper.py and qbsolv_binding.pyx

- cmd/readqubo.c
Fix issue #73.  Modify read_qubo() to accept either "0" or "unconstrained" as the topology in the program (p) line of a QUBO file
> Fix issue #73.  Modify read_qubo() to accept either "0" or "unconstrained"

- ci/travis/build-wheels.sh
- cmd/main.c
- readme.md
Remove duplicated lines in coupler list
> Fix typo in sample QUBO

- CMakeLists.txt
Removed default requirement for gtest
> Turn build tests off by default

- CMakeLists.txt
Add installation lines that were accidentally deleted
> Fix gtest bug

- src/solver.cc
> Fix obscure printout

- src/solver.cc
This was to detect a stuck loop in the tabu search.  It also changes slightly the iteration count at the bottom of the outer loop.  This seems to improve performance in larger problems, such as the qbsTest2500 , speeds up on mac about ~30%
> Added a check for loop at bottom of multiple energy well

- src/solver.cc
- src/util.cc
- src/util.h
the subQubo solves of no changes.  Addition of one more numeric test
to avoid cycling in the Tabu search
> Avoid cycle and addition of Special functions for randomizing 

- src/solver.cc
it all allows small qubo's to enter the outer loop but not do subqubo
processing
> This changes the Tabu list length for very small qubo's from 5 to 10

- .appveyor.yml
Appears to be a bug in pip 10.0.0
Not fixed in pip 10.0.1
> Don't upgrade pip

- python/README.md
`response.energies()` is obsolete now.
We should replace them by `data_vectors`.
> Update old Python example

- docs/conf.py
- docs/contributing.rst
- docs/ocean.rst
@arcondello, this moves to .com version of RtDs
> Use intersphinx instead of explicit links

- python/dwave_qbsolv/qbsolv_binding.pyx
- python/requirements.txt
- setup.py
- tests/test_dwave_qbsolv.py
> Fix timeout issues

- src/solver.cc
I found a small unreachable part while analyzing the implementation of the qbsolv algorithm.
> Fixed unreachable LoC in solver.cc
